Resolve content app errors ``django.db.utils.InterfaceError: connection already closed``.
